const imagens = [
  {
    src: "images/arquitetura-01.webp",
    titulo: "Hotel de estrada",
    categoria: "Arquitetura",
    tags: ["hotel", "estrada"],
  },
  {
    src: "images/arquitetura-02.webp",
    titulo: "Prédio moderno com arredondamento nas pontas",
    categoria: "Arquitetura",
    tags: ["prédio", "moderno"],
  },
  {
    src: "images/arquitetura-03.webp",
    titulo: "Prédio preto e branco em concreto",
    categoria: "Arquitetura",
    tags: ["prédio", "concreto"],
  },
  {
    src: "images/arquitetura-04.webp",
    titulo: "Prédio alto comercial",
    categoria: "Arquitetura",
    tags: ["prédio", "comercial"],
  },
  {
    src: "images/arquitetura-05.webp",
    titulo: "Cozinha moderna com cores neutras",
    categoria: "Arquitetura",
    tags: ["cozinha", "moderna"],
  },
  {
    src: "images/natureza-01.webp",
    titulo: "Animais selvagens em volta de um lago",
    categoria: "Natureza",
    tags: ["animais", "selvagens"],
  },
  {
    src: "images/natureza-02.webp",
    titulo: "Via láctea",
    categoria: "Natureza",
    tags: ["universo", "galáxia"],
  },
  {
    src: "images/natureza-03.webp",
    titulo: "Árvore seca no meio da paisagem",
    categoria: "Natureza",
    tags: ["árvore", "seca"],
  },
  {
    src: "images/natureza-04.webp",
    titulo: "Foto ao redor de flores com a lua no centro",
    categoria: "Natureza",
    tags: ["flores", "lua"],
  },
  {
    src: "images/natureza-05.webp",
    titulo: "Pessoas no topo de uma montanha registrando montanhas com neve ao redor",
    categoria: "Natureza",
    tags: ["montanhas", "neve"],
  },
  {
    src: "images/pessoas-01.webp",
    titulo: "Criança sorrindo de pijama",
    categoria: "Pessoas",
    tags: ["menino", "sorrindo"],
  },
  {
    src: "images/pessoas-02.webp",
    titulo: "Foto dos pés de pessoas com diferentes calçados",
    categoria: "Pessoas",
    tags: ["pessoas", "calçados"],
  },
  {
    src: "images/pessoas-03.webp",
    titulo: "Pessoas comemorando um casamento com bebidas",
    categoria: "Pessoas",
    tags: ["pessoas", "casamento"],
  },
  {
    src: "images/pessoas-04.webp",
    titulo: "Casal segurando seu bebê no colo",
    categoria: "Pessoas",
    tags: ["casal", "bebê"],
  },
  {
    src: "images/pessoas-05.webp",
    titulo: "Pessoas dançando no meio da rua",
    categoria: "Pessoas",
    tags: ["pessoas", "dançando"],
  },
  {
    src: "images/verao-01.webp",
    titulo: "Um banco na frente do mar com uma pessoa sentada embaixo do seu guarda-sol",
    categoria: "Verão",
    tags: ["mar", "guarda-sol"],
  },
  {
    src: "images/verao-02.webp",
    titulo: "Foto de uma cidade antiga com vista para o mar em um dia ensolarado",
    categoria: "Verão",
    tags: ["cidade", "mar"],
  },
  {
    src: "images/verao-03.webp",
    titulo: "Pessoas dentro do mar tomando banho em um dia ensolarado",
    categoria: "Verão",
    tags: ["pessoas", "ensolarado"],
  },
  {
    src: "images/verao-04.webp",
    titulo: "Pessoas na areia e dentro do mar tomando banho de sol",
    categoria: "Verão",
    tags: ["mar", "sol"],
  },
  {
    src: "images/verao-05.webp",
    titulo: "Foto de uma canoa no mar com casas de fundo em um dia ensolarado",
    categoria: "Verão",
    tags: ["canoa", "mar"],
  },
  {
    src: "images/viagem-01.webp",
    titulo: "Foto da rua de uma cidade com características chinesas",
    categoria: "Viagem",
    tags: ["rua", "chinesa"],
  },
  {
    src: "images/viagem-02.webp",
    titulo: "Foto da paisagem árida com morros de pedras extremamente altos",
    categoria: "Viagem",
    tags: ["pedras", "altos"],
  },
  {
    src: "images/viagem-03.webp",
    titulo: "Foto da paisagem verde com morros de pedras pontudos ",
    categoria: "Viagem",
    tags: ["morros", "pedras"],
  },
  {
    src: "images/viagem-04.webp",
    titulo: "Foto de um barco no meio da cidade rodeada de água",
    categoria: "Viagem",
    tags: ["barco", "cidade"],
  },
  {
    src: "images/viagem-05.webp",
    titulo: "Foto de um castelo antigo com uma pessoa caminhando na frente",
    categoria: "Viagem",
    tags: ["castelo", "antigo"],
  }
];
